version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: echowave-postgres
    environment:
      POSTGRES_DB: echowave
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: echowave-backend
    environment:
      PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: echowave
      DB_USER: postgres
      DB_PASSWORD: password
      DB_SSLMODE: disable
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./recordings:/app/recordings

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: echowave-frontend
    environment:
      VITE_API_URL: http://localhost:8080/api
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
